name: Build (aios)
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev/v2
      - name: Clone openwrt-connect
        run: git clone --branch dev/v2 https://github.com/site-u2023/openwrt-connect.git build
      - name: Copy aios files
        shell: cmd
        run: |
          copy /Y aios-connect\aios-connect.ini build\openwrt-connect.ini
          copy /Y aios-connect\aios-connect.conf build\openwrt-connect.conf
          copy /Y aios-connect\aios.ico build\aios.ico
          copy /Y aios-connect\aios2.ico build\aios2.ico
          copy /Y aios-connect\aios2.sh build\aios2.sh
          copy /Y aios-connect\aios.sh build\aios.sh
      - name: Build
        shell: cmd
        working-directory: build
        run: openwrt-connect-build.bat
      - name: Rename MSI
        shell: cmd
        working-directory: build
        run: move /Y openwrt-connect.msi aios-connect.msi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: aios-connect
          path: build\aios-connect.msi
